### ISSUE TITLE
Getting NoMethodError undefined method 'accept!' for #<HasFriendship::Friendship:0x99c67b0>

### ISSUE THREAD

**Issue by Eblohm** [sungwoncho/has_friendship#25]
I'm honestly not sure why this is happening. Yesterday friendships could be accepted but now today they cannot. I haven't changed any code in the controller, and users can still request other users just fine, but now when a user tries to accept a request I get that error. 

Here's my code in my controller for accepting friendships:
`def accept`
`new_friend = User.find_by(username: params[:friend])`
`current_user.accept_request(new_friend)`
`flash[:notice] = "Successfully added #{new_friend.username}!"`
 `redirect_to root_url`
 `end`

Like I said, this code was working fine yesterday, and I haven't touched anything related to friendships gem since it was working.

Edit: it looks like this might have something to do with the newest commit that was pushed yesterday, actually. Do I need to add more code now? Or run a new migration for something?

**Comment by sungwoncho** [comment]
I released a new version with https://github.com/sungwoncho/has_friendship/pull/24. The tests were passing but there might have been some breaking changes. Please use the previous `0.1.3` while I look into it.

@ArmandoMendoza Could you help debugging this? Maybe people need a new migration because of [this line](https://github.com/sungwoncho/has_friendship/pull/24/files#diff-b11b9e87c0c5d3acfbd5553f46ff3c2aR6)?

**Comment by sungwoncho** [comment]
Should be fixed with [1.0.0](https://github.com/sungwoncho/has_friendship/blob/master/CHANGELOG.md#100-201657). Can you try?

**Comment by Eblohm** [comment]
Still getting it, unfortunately. Here's the full error message if it helps at all

`undefined method 'accept!' for #<HasFriendship::Friendship:0x007f999cf8d350>`
`Did you mean?  accepted!`

**Comment by sungwoncho** [comment]
Did you run the migrations? https://github.com/sungwoncho/has_friendship#upgrading-to-1xx

**Comment by Eblohm** [comment]
Yeah, I did.

**Comment by sungwoncho** [comment]
Sorry to hear that. Please use 0.1.3 in the meantime. At the moment, I don't have enough time to investigate the issue. Could you help? also ping @Pensarfeo @ArmandoMendoza. Thanks.

**Comment by Eblohm** [comment]
Yeah, of course. Also I get the same error when attempting to block friends (except it says undefined method block!, instead of accept!)

**Comment by f-anthonioz** [comment]
So, after much digging I think I finally got it.

First off, you can quick fix by simply adding :

    gem 'stateful_enum'

to your Gemfile and then run the usual :

    bundle install

Now, regarding the cause of the issue, it seems to be coming from stateful_enum gem whose ActiveRecord extension is not properly required. Therefore, ActiveRecord's enum method is not overriden.

Not sure how to fix this yet but I'll dig a bit more and I hope it helps. :)

**Comment by sungwoncho** [comment]
@Eblohm, you can try @f-anthonioz's fix on [v1.0.1](https://github.com/sungwoncho/has_friendship/blob/master/CHANGELOG.md#101-2016514).

**Comment by Eblohm** [comment]
Yep, works great now!
